### ISSUE TITLE
Replace 'every' occurence of `vc_jwt` with `jwt_vc`

### ISSUE THREAD

**Issue by georgepadayatti** [EWC-consortium/ewc-wallet-conformance-backend#10]
This has to be changed in the following places:

1. Issuer well-known configuration: https://github.com/EWC-consortium/ewc-wallet-conformance-backend/blob/main/data/issuer-config.json
2. Credential endpoint: https://github.com/EWC-consortium/ewc-wallet-conformance-backend/blob/b429a168651b1b59ce78c0a4e09aa7ab8321b6e2/routes/routes.js#L220-L223

**Comment by endimion** [comment]
fixed by last merge
