### ISSUE TITLE
`http://localhost:8080` used in redirects

### ISSUE THREAD

**Issue by astrom-b** [EWC-consortium/ewc-wallet-conformance-backend#16]
In certain tests the conformance backend performs a redirect to `http://localhost:8080`. This is done in order to perform a dynamic credential request. The correct way to invoke a dynamic credential request is, from my understanding, to discover the wallet's authorization endpoint and then redirect to it. How come this URL is used?

**Comment by endimion** [comment]
hey @astrom-b please have a look at pull the latest version of the staging branch and if you think it is fixed let me know to close, or plz share anything else that you might notice

**Comment by astrom-b** [comment]
I am closing this issue since it's been fixed in staging.
