### ISSUE TITLE
Issues in staging branch

### ISSUE THREAD

**Issue by georgepadayatti** [EWC-consortium/ewc-wallet-conformance-backend#19]
I noticed the following issues in the staging branch:

1. `updateIssuerStateWithAuthCode` is not imported in `codeFlowSdJwtRoutes.js`
2. If pushed authorisation request contains `client_metadata`, it must be stored and accessible during authorisation requests
3. Redirect URI must be saved during pushed authorisation request or authorisation request and accessible in direct POST endpoint.

**Comment by endimion** [comment]
closing after mergin pull request #20
