### ISSUE TITLE
Incorrect Placement of `limit_disclosure` Property in Input Descriptor

### ISSUE THREAD

**Issue by georgepadayatti** [EWC-consortium/ewc-wallet-conformance-backend#2]
The `limit_disclosure` property is present directly within the input descriptor. For reference, see the example here:

https://github.com/EWC-consortium/ewc-wallet-conformance-backend/blob/09a5695f666e011beb444d6a1f3f4b64c8dd766f/data/presentation_definition.json#L9-L35

According to the [PEX spec](https://identity.foundation/presentation-exchange/#input-descriptor-object), the `limit_disclosure` property should be placed inside the `constraints` object, if present.

**Comment by lalc** [comment]
@team: please comment if we can get this fixed and make a correction release for RFC002.
