### ISSUE TITLE
Test case 3 in ITB: Claims missing in the issued credential

### ISSUE THREAD

**Issue by georgepadayatti** [EWC-consortium/ewc-wallet-conformance-backend#27]
As per the issuer metadata `VerifiablePIDSDJWT` credential configuration looks like below:

https://github.com/EWC-consortium/ewc-wallet-conformance-backend/blob/7313dffee74d3a04363da42ff7755c347d4bf191/data/issuer-config.json#L112-L201

But the credential issued does not contain `issuance_date`, `expiry_date`, `issuing_authority` and `issuing_country`. 

The following code is responsible for preparing the SD-JWT credential in question and it doesn't contain any of these claims:

https://github.com/EWC-consortium/ewc-wallet-conformance-backend/blob/db2346f517f73ed032a7e7873829ad86e3452ff5/utils/credPayloadUtil.js#L307-L321

**Comment by endimion** [comment]
fixed many thanks!
