### ISSUE TITLE
Test case 3: Validation response is pending

### ISSUE THREAD

**Issue by georgepadayatti** [EWC-consortium/ewc-wallet-conformance-backend#31]
Reference video recording available [here](https://drive.google.com/file/d/1xHMFEr0rPpkSubg0OnSeSP9popQR8FR6/view?usp=sharing).

**Comment by endimion** [comment]
should be fixed now... Don't have a wallet that supports this flow though.. if possible have a check, and if it works close this.. .

**Comment by endimion** [comment]
After discussion in slack tihs is resolved so closing...
