### ISSUE TITLE
Incorrect hash algorithm name used in SD-JWT

### ISSUE THREAD

**Issue by astrom-b** [EWC-consortium/ewc-wallet-conformance-backend#33]
The value for `_sd_alg` is incorrect in several places. According to the SD-JWT standard, hash algorithm names must match with those from the IANA hash algorithm registry [1]. The `_sd_alg` value used is `SHA-256`, while the correct one, according to [1] would be `sha-256`.

[1] https://www.iana.org/assignments/named-information/named-information.xhtml

**Comment by lukasjhan** [comment]
Yeah sha-256 is right. In fact, It's case-sensitive. see https://github.com/oauth-wg/oauth-selective-disclosure-jwt/issues/523#issuecomment-2469282939

**Comment by endimion** [comment]
hey all, thanks for bringing this up... it should already have been corrected in the staging branch. Please verify and close if so. Also, @astrom-b  there are a couple issues you have raised that I belive have already been adressed ... if so can you please close them so I can merge the staging to the main :)

**Comment by astrom-b** [comment]
Closing this issue since it was already fixed in staging. My bad :)
