### ISSUE TITLE
Test case 18 is broken since`/issueStatus` endpoint is failing; Unable to find the session by id due to `-persona=` suffix in EducationalID

### ISSUE THREAD

**Issue by georgepadayatti** [EWC-consortium/ewc-wallet-conformance-backend#8]
In the below code, during EducationalID issuance, `-persona=` suffix is being added for the session key.

https://github.com/EWC-consortium/ewc-wallet-conformance-backend/blob/c0d36d51eee72b67d8a1c45bd46bfd9c5cf0d3a3/routes/educationalRoutes.js#L43-L46

But in the `/token` and `/issueStatus` endpoint, when fetching the session, the suffix is not being added to the sessionId and therefore it is not able to update the status for the session.

https://github.com/EWC-consortium/ewc-wallet-conformance-backend/blob/c0d36d51eee72b67d8a1c45bd46bfd9c5cf0d3a3/routes/routes.js#L159-L163

https://github.com/EWC-consortium/ewc-wallet-conformance-backend/blob/c0d36d51eee72b67d8a1c45bd46bfd9c5cf0d3a3/routes/routes.js#L811-L824

**Comment by endimion** [comment]
thanks george corrected... now test case works correctly..
