### ISSUE TITLE
Credential issuer metadata returns "vc_jwt" instead of "jwt_vc_json"

### ISSUE THREAD

**Issue by astrom-b** [EWC-consortium/ewc-wallet-conformance-backend#9]
The credential issuer metadata returns "vc_jwt" in the "format" field of the list of supported credentials, instead of "jwt_vc_json", which is the correct value according to OpenID4VCI draft 12.

**Comment by endimion** [comment]
Yes, agreed with @astrom-b . The issues with the wallets failing today after this change might be due to an issue of firebase today as reported by Albert... Anyone objects to correcting the credentials supported to jwt_vc_json?

**Comment by georgepadayatti** [comment]
> Yes, agreed with @astrom-b . The issues with the wallets failing today after this change might be due to an issue of firebase today as reported by Albert... Anyone objects to correcting the credentials supported to jwt_vc_json?

I think it's because you also have to change this comparison in `/credential` endpoint as well along with issuer well-known configuration: https://github.com/EWC-consortium/ewc-wallet-conformance-backend/blob/b429a168651b1b59ce78c0a4e09aa7ab8321b6e2/routes/routes.js#L220-L223

**Comment by endimion** [comment]
hey George :) nope I had changed that as well (at least that is what I think...)  there is a branch in this repo that you could try to test it out. If all is ok let me know to merge...

**Comment by georgepadayatti** [comment]
> hey George :) nope I had changed that as well (at least that is what I think...) there is a branch in this repo that you could try to test it out. If all is ok let me know to merge...

Yes will check and revert.

**Comment by georgepadayatti** [comment]
> hey George :) nope I had changed that as well (at least that is what I think...) there is a branch in this repo that you could try to test it out. If all is ok let me know to merge...

Do we fix this https://github.com/EWC-consortium/ewc-wallet-conformance-backend/issues/10 and then plan the merge of `jwt_vc_json` branch ?

**Comment by endimion** [comment]
yes fixed and merged
